# Generated by Django 5.2.7 on 2025-10-16 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('state', models.CharField(choices=[('requesting', 'requesting'), ('accepted', 'accepted'), ('rejected', 'rejected')], db_index=True, default='requesting', max_length=20)),
                ('published', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_sent', to='authors.author')),
                ('author_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_received', to='authors.author')),
            ],
            options={
                'ordering': ['-published', '-created'],
                'indexes': [models.Index(fields=['author_followed', 'state'], name='inbox_follo_author__6e51c6_idx'), models.Index(fields=['actor', 'state'], name='inbox_follo_actor_i_5d3b29_idx'), models.Index(fields=['published'], name='inbox_follo_publish_9f89bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'author_followed'), name='unique_follow_request_pair')],
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(db_index=True, max_length=20)),
                ('object_fqid', models.URLField(blank=True, help_text='FQID of the primary object, if applicable.', max_length=1024)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='authors.author')),
            ],
            options={
                'ordering': ['-received_at', '-created'],
                'indexes': [models.Index(fields=['recipient', 'received_at'], name='inbox_inbox_recipie_fcccce_idx'), models.Index(fields=['type'], name='inbox_inbox_type_2f3ec9_idx')],
            },
        ),
    ]
