# Generated by Django 5.2.6 on 2025-10-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='state',
            field=models.CharField(choices=[('requesting', 'requesting'), ('accepted', 'accepted')], db_index=True, default='requesting', max_length=20),
        ),
    ]
