# Generated by Django 5.2.7 on 2025-10-16 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.URLField(max_length=1024, primary_key=True, serialize=False)),
                ('host', models.URLField(help_text='Full API base, e.g., https://node/api/', max_length=1024)),
                ('displayName', models.CharField(db_index=True, max_length=200)),
                ('github', models.URLField(blank=True, max_length=1024)),
                ('profileImage', models.URLField(blank=True, max_length=1024)),
                ('web', models.URLField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('is_local', models.BooleanField(db_index=True, default=True)),
                ('serial', models.CharField(blank=True, db_index=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="Serial must not start with 'http' and must not contain ':'.", regex='^(?!http)(?!.*:).+$')])),
            ],
            options={
                'indexes': [models.Index(fields=['displayName'], name='authors_aut_display_2be542_idx'), models.Index(fields=['host'], name='authors_aut_host_b2ba16_idx'), models.Index(fields=['is_local'], name='authors_aut_is_loca_f7416f_idx'), models.Index(fields=['serial'], name='authors_aut_serial_e7ed49_idx')],
            },
        ),
    ]
