# Generated by Django 5.2.7 on 2025-10-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
