# Generated by Django 5.2.6 on 2025-10-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='author',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
