# Generated by Django 5.2.7 on 2025-10-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_is_active_author_is_admin'),
        ('authors', '0003_author_is_approved'),
    ]

    operations = [
    ]
