# Generated by Django 5.2.6 on 2025-10-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_is_active_author_is_admin'),
        ('authors', '0003_author_is_approved'),
    ]

    operations = [
    ]
