# Generated by Django 5.2.6 on 2025-10-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_merge_20251020_0601'),
        ('authors', '0004_merge_20251020_1409'),
        ('authors', '0004_merge_20251020_1536'),
    ]

    operations = [
    ]
