# Generated by Django 5.2.6 on 2025-10-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_merge_20251020_1704'),
        ('authors', '0005_merge_20251020_1817'),
        ('authors', '0005_merge_20251020_1854'),
    ]

    operations = [
    ]
