# Generated by Django 5.2.7 on 2025-10-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_merge_20251020_1925'),
        ('authors', '0006_merge_20251020_2104'),
    ]

    operations = [
    ]
