import type { AddOnAttachment } from '@heroku-cli/schema';
import type { ExtendedAddonAttachment } from '@heroku/heroku-cli-util';
import type { CredentialsInfo } from './types';
import type { ExtendedAddon } from './types';
export declare const essentialNumPlan: (addon: ExtendedAddonAttachment['addon'] | ExtendedAddon) => boolean;
export declare const legacyEssentialPlan: (addon: ExtendedAddonAttachment['addon'] | ExtendedAddon) => boolean;
export declare function essentialPlan(addon: ExtendedAddonAttachment['addon'] | ExtendedAddon): boolean;
export declare function formatResponseWithCommands(response: string): string;
export declare function presentCredentialAttachments(app: string, credAttachments: Required<AddOnAttachment>[], credentials: CredentialsInfo, cred: string): string;
export declare const configVarNamesFromValue: (config: Record<string, string>, value: string) => string[];
export declare const databaseNameFromUrl: (uri: string, config: Record<string, string>) => any;
