# Generated by Django 5.2.7 on 2025-10-16 19:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('fqid', models.URLField(max_length=1024, primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, db_index=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="Serial must not start with 'http' and must not contain ':'.", regex='^(?!http)(?!.*:).+$')])),
                ('title', models.CharField(blank=True, max_length=300)),
                ('web', models.URLField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=50)),
                ('published', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(db_index=True, default=False)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS'), ('UNLISTED', 'UNLISTED'), ('DELETED', 'DELETED')], db_index=True, default='PUBLIC', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='authors.author')),
            ],
            options={
                'ordering': ['-published', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('fqid', models.URLField(max_length=1024, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/markdown', max_length=50)),
                ('published', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('web', models.URLField(blank=True, max_length=1024)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='authors.author')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='entries.entry')),
            ],
            options={
                'ordering': ['-published', '-created'],
            },
        ),
        migrations.CreateModel(
            name='EntryDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('recipient_author_fqid', models.URLField(db_index=True, max_length=1024)),
                ('delivered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='entries.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('fqid', models.URLField(max_length=1024, primary_key=True, serialize=False)),
                ('object_fqid', models.URLField(db_index=True, max_length=1024)),
                ('published', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='authors.author')),
            ],
            options={
                'ordering': ['-published', '-created'],
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['serial'], name='entries_ent_serial_7847bc_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['published'], name='entries_ent_publish_1a51f6_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['visibility'], name='entries_ent_visibil_1e0d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author', 'published'], name='entries_ent_author__2e7d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['published'], name='entries_com_publish_7e823a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['entry', 'published'], name='entries_com_entry_i_b1af67_idx'),
        ),
        migrations.AddIndex(
            model_name='entrydelivery',
            index=models.Index(fields=['recipient_author_fqid', 'delivered_at'], name='entries_ent_recipie_2e9d00_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrydelivery',
            constraint=models.UniqueConstraint(fields=('entry', 'recipient_author_fqid'), name='unique_entry_recipient_delivery'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['object_fqid'], name='entries_lik_object__80b78b_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['published'], name='entries_lik_publish_e5a036_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['author', 'published'], name='entries_lik_author__1bb18e_idx'),
        ),
    ]
