# Generated by Django 5.2.7 on 2025-11-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_merge_0002s'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain')], default='text/markdown', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain')], default='text/plain', max_length=50),
        ),
    ]
