# Generated by Django 5.2.6 on 2025-11-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_image_url_alter_comment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
