# Generated by Django 5.2.6 on 2025-11-22 00:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this node', max_length=255, unique=True)),
                ('base_url', models.URLField(help_text='Base URL of the node (e.g., https://example.com)', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('api_version', models.CharField(default='v1', help_text='API version this node uses', max_length=20)),
                ('auth_method', models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('token', 'Bearer Token'), ('api_key', 'API Key')], default='none', help_text='Authentication method to use', max_length=20)),
                ('username', models.CharField(blank=True, help_text='Username for Basic Auth', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Password for Basic Auth', max_length=255)),
                ('token', models.CharField(blank=True, help_text='Bearer token or API key', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this node')),
                ('is_bidirectional', models.BooleanField(default=True, help_text='Can this node send data to us?')),
                ('inbox_endpoint', models.CharField(default='/federation/', help_text='Endpoint for sending entries', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Notes about this node')),
                ('admin_contact', models.EmailField(blank=True, help_text='Admin contact for this node', max_length=254)),
                ('last_successful_send', models.DateTimeField(blank=True, null=True)),
                ('last_failed_send', models.DateTimeField(blank=True, null=True)),
                ('total_sends', models.IntegerField(default=0)),
                ('total_failures', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Federated Node',
                'verbose_name_plural': 'Federated Nodes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FederationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('entry_fqid', models.CharField(help_text='FQID of the entry being sent', max_length=500)),
                ('request_payload', models.JSONField(blank=True, help_text='Request payload sent', null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response from the node')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='federation.federatednode')),
            ],
            options={
                'verbose_name': 'Federation Log',
                'verbose_name_plural': 'Federation Logs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='federation__created_097c35_idx'), models.Index(fields=['node', '-created'], name='federation__node_id_52289c_idx')],
            },
        ),
    ]
