# Generated by Django 5.2.6 on 2025-11-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federatednode',
            name='auth_method',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth')], default='none', help_text='Authentication method to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='federatednode',
            name='inbox_endpoint',
            field=models.CharField(default='/api/authors/', help_text='Endpoint for sending entries', max_length=200),
        ),
    ]
