# Generated by Django 5.2.6 on 2025-11-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_alter_federatednode_auth_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatednode',
            name='is_local',
            field=models.BooleanField(default=True, help_text='Checks if this node is for this server'),
        ),
    ]
