# Generated by Django 5.2.6 on 2025-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0003_federatednode_is_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federatednode',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Checks if this node is for this server'),
        ),
    ]
