# Generated by Django 5.2.6 on 2025-10-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostedimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='hostedimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='hostedimage',
            name='is_public',
        ),
    ]
