# Generated by Django 5.2.6 on 2025-11-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_alter_hostedimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedimage',
            name='admin_uploaded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
